baseURL: "https://wanghaoting.com" 
title: Hao-Ting Wang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: https://wanghaoting.com/CV/cv.pdf
          weight: 0
        - name: About
          url: about/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2

params:
    description: "This website hosts Hao-Ting Wang's research, curriculum vitae, and contact information."
    author: Hao-Ting Wang
    googleAnalyticsID: "UA-60731918-2"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["bio"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hao-Ting Wang
          subtitle: "I am a [Canadian Neuroanalytics Scholar](https://www.albertaneuro.ca/first-cohort-of-canadian-neuroanalytics-scholars-announced/) at [CRIUGM](https://criugm.qc.ca/), Montreal, Canada. My current research focuses on neuroinformatics, brain-based biomarkers, and cognitive neuroscience."
          imageUrl: "image.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Talks
              url: talks/
            - name: Resume
              url: resume_haotingwang_1page.pdf

    socialIcons:
        - name: Email
          url: mailto:haotingwang.research@protonmail.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=FrlzI8IAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/htwangtw
        - name: LinkedIn
          url: https://www.linkedin.com/in/hao-ting-wang-73597145/
        - name: CV
          url: https://wanghaoting.com/CV/cv.pdf
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/haotingwang.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hao-Ting Wang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
